#index:
#    path: /
#    controller: App\Controller\DefaultController::index

PDFGenerate:
    path: '/event/{id}/generate-pdf'
    controller: App\Controller\EventController::PDFGenerate
    
generate_pdf:
    path: '/commande/{id}/generate-pdf'
    controller: App\Controller\CommandeController::generatePdf

app_reservation_statistics:
    path: '/reservation/statistics'
    controller: App\Controller\ReservationController::statistics

# config/routes.yaml

app_guide_statistics:
    path: /guide/statistics
    controller: App\Controller\GuideController::guideStatistics

